### ISSUE TITLE
Darts_DNN model file not found

### ISSUE THREAD

**Issue by athalexiou** [Xinglab/DARTS#9]
Hello,

I've been trying to run the testing snippets for both BHT and DNN. 

BHT worked just fine, but when I tried to run the test predict provided in "readme" of DNN I get a "No such file or directory" error for the model file which is supposed to be in "/home/thalexiou/.darts/DNN/v0.1.0/trainedParam/A5SS-trainedParam-EncodeRoadmap.h5".

I have the test_data required but I cannot find a ".darts" directory anywhere on my machine, neither in the "darts" v-env directory created nor anywhere else. Am I supposed to get this from somewhere and create this path myself or am I missing something?

Ps. The links in both "readme" files towards more examples and online docs are not correct, can you please redirect me to more documentation as well?

Thanks in advance,
Thanos Alexiou

**Comment by zj-zhang** [comment]
Hi @athalexiou 
I have fixed the links to ReadTheDocs sites.
The models are download using "get_data" subcommand:
https://darts-dnn.readthedocs.io/en/latest/get_started.html#using-predict
